Ardita/Views/ViewComponents/MenuViewComponent.cs
using Ardita.Models;
using Ardita.Models.DbModels;
using Ardita.Services.Classess;
using Ardita.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ardita.Views.ViewComponents
{
    public class MenuViewComponent : ViewComponent 
    {
        private readonly IUserService _userService;
        public MenuViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var role = claimsIdentity.FindFirst("RoleId").Value;

            var results = new MenuModel();
            

            Guid guid = new Guid(role);

            var getMenu = await _userService.GetUserMenu(guid);
            var menu = getMenu.GroupBy(x=> x.MenuId).Select(x => new MstMenu { MenuId = x.Key, Name = x.FirstOrDefault().MenuName }).ToList();

            var getSubMenu = await _userService.GetUserMenu(guid);
            var subMenu = getSubMenu.GroupBy(g=>g.SubMenuId).Select(x => 
            new MstSubmenu { 
                SubmenuId = x.FirstOrDefault().SubMenuId, 
                Name = x.FirstOrDefault().SubMenuName,
                MenuId = x.FirstOrDefault().MenuId,
                Path = x.FirstOrDefault().SubMenuPath,
                Sort = x.FirstOrDefault().SubMenuSort
            }).OrderBy(x => x.Sort).ToList();


            results.menu = menu;
            results.subMenu = subMenu;

            return View(results);
        }
    }
}

Ardita/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="float-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014 - 2018
    </div>
</div>

Ardita/Views/Shared/_Layout.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ardita</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
            {@RenderSection("Styles", required: false)}

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/plugins/select2/select2.min.css">
        <link rel="stylesheet" href="~/css/plugins/select2/select2-bootstrap4.min.css">
        <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" />
        <link href="~/lib/sweetalert/dist/sweetalert.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/plugins/select2/select2.min.css">
        <link rel="stylesheet" href="~/css/plugins/select2/select2-bootstrap4.min.css">
        <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" />
        <link href="~/lib/sweetalert/dist/sweetalert.css" rel="stylesheet" />
    </environment>


</head>
<body class="pace-running">

    <!-- Skin configuration box -->
    <!-- <partial name="_SkinConfig" /> -->

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @await Component.InvokeAsync("Menu");

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("~/Views/Shared/_TopNavbar.cshtml")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            <partial name="_Footer" />

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <!--Datatable-->
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
        <!--Moment-->
        <script src="~/lib/moment/min/moment.min.js"></script>

        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/pace/pace.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>
        <!-- Select2 -->
        <script src="~/lib/select2/select2.full.min.js"></script>
        <!-- Date Picker -->
        <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
        <!-- BS custom file -->
        <script src="~/lib/bs-custom-file/bs-custom-file-input.min.js"></script>
        <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <!--Datatable-->
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
        <!--Moment-->
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/pace/pace.min.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>
        <!-- Select2 -->
        <script src="~/lib/select2/select2.full.min.js"></script>
        <!-- Date Picker -->
        <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
        <!-- BS custom file -->
        <script src="~/lib/bs-custom-file/bs-custom-file-input.min.js"></script>
        <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Ardita/Views/Shared/_Navigation.cshtml
@model Ardita.Models.MenuModel;
@using Ardita.Globals

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <img alt="image" class="rounded-circle" src="~/img/img-profile.png" />
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">@User.FindFirst("EmployeeName").Value</span>
                        <span class="text-muted text-xs block">@User.FindFirst("RoleName").Value</span>
                    </a>
                   
                </div>
                <div class="logo-element">
                    AR
                </div>
            </li>
            @foreach(var menu in Model.menu)
            {
                <li>
                    <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">@menu.Name </span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        @foreach(var subMenu in Model.subMenu.Where(x => x.MenuId == menu.MenuId))
                        {
                            <li><a href="@Url.Action("Index", subMenu.Path, new { Area = subMenu.Path })">@subMenu.Name</a></li>
                        }
                    </ul>
                </li>
            }
        </ul>
    </div>
</nav>

Ardita/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="/Authentication/Logout">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>